name: Manual Movie Scrape

on:
  workflow_dispatch:   # ম্যানুয়ালি রান করার জন্য

jobs:
  run-scraper:
    runs-on: ubuntu-22.04   # স্টেবল OS

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper Script
        run: |
          python movie_scraper.py

      - name: Upload Output JSON
        uses: actions/upload-artifact@v3
        with:
          name: stream-data
          path: stream_data.json
